export const GET_COACHS = 'PROGRAM/GET_COACHS';
export const GET_COACHS_SUCCESS = 'PROGRAM/GET_COACHS_SUCCESS';

export const GET_PROGRAMS = 'PROGRAM/GET_PROGRAMS';

export const REGISTER = 'PROGRAM/REGISTER';
export const UNREGISTER = 'PROGRAM/UNREGISTER';


export const GET_PROGRAM = 'PROGRAM/GET_PROGRAM';
export const GET_PROGRAM_SUCCESS = 'PROGRAM/GET_PROGRAM_SUCCESS';

export const GET_USER_PROGRAMS = 'PROGRAM/GET_USER_PROGRAMS';
export const GET_USER_PROGRAMS_SUCCESS = 'PROGRAM/GET_USER_PROGRAMS_SUCCESS';

export const GET_PROGRAM_FOR_EDIT = 'PROGRAM/GET_PROGRAM_FOR_EDIT';
export const GET_PROGRAM_FOR_EDIT_SUCCESS = 'PROGRAM/GET_PROGRAM_FOR_EDIT_SUCCESS';
export const GET_PROGRAM_ERROR = 'PROGRAM/GET_PROGRAM_ERROR';
export const GET_PROGRAMS_SUCCESS = 'PROJECT/GET_PROGRAMS_SUCCESS';
export const ADD_PROGRAM = 'PROJECT/ADD_PROGRAM';
export const ADD_PROGRAM_SUCCESS = 'PROJECT/ADD_PROGRAM_SUCCESS';
export const UPDATE_PROGRAM = 'PROJECT/UPDATE_PROGRAM';
export const UPDATE_PROGRAM_SUCCESS = 'PROJECT/UPDATE_PROGRAM_SUCCESS';
export const DELETE_PROGRAM = 'PROJECT/DELETE_PROGRAM';
export const DELETE_PROGRAM_SUCCESS = 'PROJECT/DELETE_PROGRAM_SUCCESS';
