
export const GET_SPORTS = 'SPORT/GET_SPORTS';
export const GET_SPORTS_FOR_FILTER = 'SPORT/GET_SPORTS_FOR_FILTER';
export const GET_SPORT = 'SPORT/GET_SPORT';
export const GET_SPORT_SUCCESS = 'SPORT/GET_SPORT_SUCCESS';
export const GET_SPORT_ERROR = 'SPORT/GET_SPORT_ERROR';
export const GET_SPORTS_SUCCESS = 'PROJECT/GET_SPORTS_SUCCESS';
export const ADD_SPORT = 'SPORT/ADD_SPORT';
export const ADD_SPORT_SUCCESS = 'SPORT/ADD_SPORT_SUCCESS';
export const UPDATE_SPORT = 'SPORT/UPDATE_SPORT';
export const UPDATE_SPORT_SUCCESS = 'SPORT/UPDATE_SPORT_SUCCESS';
export const DELETE_SPORT = 'SPORT/DELETE_SPORT';
export const DELETE_SPORT_SUCCESS = 'SPORT/DELETE_SPORT_SUCCESS';
