
export const GET_COMPANIES = 'COMPANY/GET_COMPANIES';
export const GET_COMPANY = 'COMPANY/GET_COMPANY';
export const GET_COMPANY_SUCCESS = 'COMPANY/GET_COMPANY_SUCCESS';
export const GET_COMPANY_ERROR = 'COMPANY/GET_COMPANY_ERROR';
export const GET_COMPANIES_SUCCESS = 'PROJECT/GET_COMPANIES_SUCCESS';
export const ADD_COMPANY = 'COMPANY/ADD_COMPANY';
export const ADD_COMPANY_SUCCESS = 'COMPANY/ADD_COMPANY_SUCCESS';
export const UPDATE_COMPANY = 'COMPANY/UPDATE_COMPANY';
export const UPDATE_COMPANY_SUCCESS = 'COMPANY/UPDATE_COMPANY_SUCCESS';
export const DELETE_COMPANY = 'COMPANY/DELETE_COMPANY';
export const DELETE_COMPANY_SUCCESS = 'COMPANY/DELETE_COMPANY_SUCCESS';
export const REGISTER = 'COMPANY/REGISTER';
export const UNREGISTER = 'COMPANY/UNREGISTER';

